### PR TITLE
Tutorial changes based on comments in Cyclus PR

### PR DESCRIPTION
**Pull request by abachma2**
I made changes based on comments from @nuclearkatie and @katyhuff on the PR in cyclus/cyclus.github.com (https://github.com/cyclus/cyclus.github.com/pull/293)

### CODE REVIEW

**Comment by katyhuff** [comment]
I thought we were going to delete this repo?

**Comment by abachma2** [comment]
I thought the plan was to delete it once PR #293 in cyclus/cyclus.github.com was merged, since that PR is a merge with the tutorial branch in this repo.

**Comment by katyhuff** [comment]
Yes, but surely you don't need me to approve your changes in both places since we'll be deleting this repo anyway when this PR is finally merged...
Can you not just push commit here (since the review is not meant to happen here but is instead meant to happen over at cyclus/cyclus.github.com)?

**Review by katyhuff — APPROVED** [review]
Since these changes were already approved over at the other PR in cyclus/cyclus.github.com, I approve.

**Comment by abachma2** [comment]
I could merge this PR myself, but I know that merging your own PR is frowned upon.

**Comment by katyhuff** [comment]
I see. Makes perfect sense and I'm glad you're taking this seriously. I'll merge it now. 

As an aside: This weird secondary repo structure makes this is a gray area. The rule always applies to a main branch of the main repo. It generally doesn't apply to other branches of the main repo. My surprise was just because it really doesn't need to apply to non-main branches of the non-main repo.

**Pull request merged**
